### PR TITLE
added key exchange algo. to configuration

### PR DESCRIPTION
**Pull request by vajonam**
added ability to specify key exchange algorithm for some SunOS like boxes

### CODE REVIEW

**Review by Jacques44 — APPROVED** [review]

**Comment by Jacques44** [comment]
Thanks for your contribution

**Comment by Jacques44** [comment]
It's on the way. I've added password authentication as well. Release should be 1.3.0. Please tell me

**Comment by Jacques44** [comment]
Done

**Comment by vajonam** [comment]
tested it out 1.3.0 looks good. might want to consider moving the password filed in the config under the username, to avoid confusion, my algo changes work well. thanks.

**Comment by Jacques44** [comment]
Hello. In fact keys is a best solution for automation instead of pswd. It s
a way to encourage the use of key pairs :-)

**Comment by vajonam** [comment]
agreed :-)

**Comment by mdazmir** [comment]
Hi, I'm using Linux Raspberry with Node-RED and having problem with "KEX Algorithm" when trying to connect to one of my industrial controller. Below are the error from Node-RED with I'm leaving the "Key Exchange Algorithm" blank for node-red-contrib-bigssh:
`"Error: Handshake failed: no matching key exchange algorithm"`
`"Error: read ECONNRESET"`
<br/>
Below is my troubleshooting results:
- I'm able to connect using Node-RED (node-red-contrib-bigssh) to my other server (CentOS) but failed when trying to connect to this industrial controller
- I'm able to connect using SSH to my industrial controller via Linux Raspberry's terminal. I ran the ssh command with -vvv. You can view the debug output here: https://gist.github.com/mdazmir/765481cbe85463c1da38460005ee010d
- By going through the debug output above, I've set up node-red-contrib-bigssh "Key Exchange Algorithm" with curve25519-sha256, diffie-hellman-group16-sha512 and a few others but failed as well. Below are the error from Node-RED
`"Error: Unsupported key exchange algorithm: curve25519-sha256"`
`"Error: Unsupported key exchange algorithm: diffie-hellman-group16-sha512"`
<br/>
Below is my OS and Node-RED specs:<br/>
OS: Linux raspberry 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux<br/>
Node-RED: v1.2.6
<br/><br/>
Perhaps my configuration is wrong but I'm not sure how to fix it. Can you please assist me on this matter? Thanks.

**Comment by Jacques44** [comment]
Hello. I rely on the ssh2 library. (https://www.npmjs.com/package/ssh2)
As I can see you used the password method for your tries so you can use a password too for nodejs
If you want to use keys, you should try using terminal also
Regards

**Pull request merged**
